apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: more-fun
  name: more-fun
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: more-fun
  template:
    metadata:
      labels:
        app.kubernetes.io/name: more-fun
        app.kubernetes.io/part-of: more-fun
    spec:
      containers:
      - image: more-fun:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
