apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: more-fun
spec:
  template:
    spec:
      containers:
        - image: more-fun
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
